### ISSUE TITLE
[Bug]: Drag and drop for elements doesn't work

### ISSUE THREAD

**Issue by dankim444** [Watts-Lab/researcher-portal#106]
### What happened?

Currently, drag and drop only allows stages to be draggable and droppable but not for elements. Issue was only diagnosed after merging recent changes from main.

### What browsers do you see the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### What operating system do you see the problem on?

- [ ] Windows
- [X] Mac
- [ ] Linux

### How did we discover the bug?

- [ ] Reported by participant
- [ ] Observed on Sentry
- [X] Found in dev

### Priority

Inconvenience for researchers

**Comment by shapeseas** [comment]
Hey @dankim444 I tested this on `eric/refactor-editor` which is branched off of main with updates and the drag/drop works fine between elements with the treatment below. 

```
treatments:
  - name: template sample stage
    playerCount: 1
    gameStages:
      - name: TestTemplateA
        duration: 60
        elements:
          - type: submitButton
          - type: prompt
            file: projects/example/multipleChoiceColors.md
      - name: test2
        duration: 100
        elements: []
```
